global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8080']
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8080']
